name: T_bot_101 

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow the workflow to be triggered manually
  schedule:
    - cron: '0 */1 * * *'  # This will run the workflow every 6 hours

jobs:
  download-files:
    runs-on: ubuntu-latest
    timeout-minutes: 56  # Timeout after 340 minutes

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Download files from Mega
        env:
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
         
        run: |
          python bot.py
